[[
headers
]]
  for = "/*"
  [
headers.values
]
    Content-Security-Policy = "connect-src * 'unsafe-inline' 'unsafe-eval'; default-src * 'unsafe-inline' 'unsafe-eval'"
    Access-Control-Allow-Origin = "*"
